name: Code Quality Checks
on:
    push:
        branches:
            - feature/test-github-actions
    pull_request:
        branches:
            - feature/test-github-actions

jobs:
    code-check:
        name: Check code quality
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4

            -
                name: Validate composer
                run: composer validate


